package com.clink;

public class QueryConstant {

	public static String INSERT_QUERY_90_DAYS = "INSERT INTO `centurylinkdata_90_Days_Rolling`\n" + "(\n"
			+ "`id`, `LobName1`,\n" + "`Campaign name`,\n" + "`Vendor Name`,\n" + "`Location Name`,\n" + "`Call Date`,\n"
			+ "`Duration`,\n" + "`ExternalID`,\n" + "`agent_external_id`,\n" + "`Call Type Name`,\n"
			+ "`CallDirectionName`,\n" + "`EvaluationId`,\n" + "`EvaluatorUserName`,\n" + "`EvaluatorFirstName`,\n"
			+ "`EvaluatorLastName`,\n" + "`Status Date`,\n" + "`EvaluationDuration`,\n" + "`RawPoints`,\n"
			+ "`NetScore`,\n" + "`Possible Points`,\n" + "`AutoFailed`,\n" + "`AuditorUserName`,\n"
			+ "`AuditorFirstName`,\n" + "`AuditorLastName`,\n" + "`Audit Status`,\n" + "`Audit Date`,\n"
			+ "`agent_first_name`,\n" + "`agent_last_name`,\n" + "`Supervisor`,\n" + "`Manager`,\n" + "`Manager2`,\n"
			+ "`MediaType1`,\n" + "`MediaCodecName1`,\n" + "`registered_affiliation`,\n" + "`Evaluator type`,\n"
			+ "`Type of Evaluation`,\n" + "`Customer State`,\n" + "`C.R.M.`,\n" + "`Language`,\n" + "`BTN/CBR`,\n"
			+ "`Auditor Comments`,\n" + "`Evaluator Comments`,\n" + "`Performance Area Notes`,\n"
			+ "`Invalidation Comments`,\n" + "`Form Change Comments`,\n" + "`Agent Comments`,\n"
			+ "`CTL QA Management Comments`,\n" + "`HQ Audit Feedback Loop`,\n" + "`Repeat Call/ Chat`,\n"
			+ "`Repeat Call/ Chat -Comment`,\n" + "`Product or Service Type (multi-select)`,\n"
			+ "`Product or Service Type (multi-select) -Comment`,\n" + "`Products on the CTL Account`,\n"
			+ "`Products on the CTL Account -Comment`,\n" + "`Products Available but not on CTL Account`,\n"
			+ "`Products Available but not on CTL Account -Comment`,\n" + "`Current HSI Speed`,\n"
			+ "`Current HSI Speed -Comment`,\n" + "`If HSI Upgrade Available - Highest Speed?`,\n"
			+ "`If HSI Upgrade Available - Highest Speed? -Comment`,\n" + "`Primary Reason for the Call`,\n"
			+ "`Primary Reason for the Call -Comment`,\n" + "`Billing Inquiry - Sub-reasons - PC`,\n"
			+ "`Billing Inquiry - Sub-reasons - PC -Comment`,\n" + "`BI - OTC Dispute - Sub-reasons - PC`,\n"
			+ "`BI - OTC Dispute - Sub-reasons - PC -Comment`,\n"
			+ "`COMP: Did the agent verify the caller thru authorized means?`,\n"
			+ "`COMP: Did the agent verify the caller -Comment`,\n" + "`NO - Verify caller`,\n"
			+ "`NO - Verify caller -Comment`,\n" + "`COMP: Did the agent verify and/or capture the email address?`,\n"
			+ "`COMP: Did the agent verify and/or capture the email -Comment`,\n" + "`NO - Email`,\n"
			+ "`NO - Email -Comment`,\n" + "`Did the agent utilize the SMS script?`,\n"
			+ "`Did the agent utilize the SMS script? -Comment`,\n"
			+ "`YES or NO - Did the agent utilize the SMS script?`,\n"
			+ "`YES or NO - Did the agent utilize the SMS script? -Comment`,\n" + "`Sales Category Applicable`,\n"
			+ "`Sales Category Applicable -Comment`,\n" + "`Did the agent ask discovery questions?`,\n"
			+ "`Did the agent ask discovery questions? -Comment`,\n" + "`YES - Discovery Questions`,\n"
			+ "`YES - Discovery Questions -Comment`,\n"
			+ "`Did the agent discuss a feature of the product or service?`,\n"
			+ "`Did the agent discuss a feature of the product -Comment`,\n" + "`YES - Feature Discussion`,\n"
			+ "`YES - Feature Discussion -Comment`,\n" + "`Did the agent offer product(s)?`,\n"
			+ "`Did the agent offer product(s)? -Comment`,\n" + "`Product Offer Tracking`,\n"
			+ "`Product Offer Tracking -Comment`,\n" + "`Did the agent lead with the correct offer?`,\n"
			+ "`Did the agent lead with the correct offer? -Comment`,\n" + "`Correct Offer Tracking`,\n"
			+ "`Correct Offer Tracking -Comment`,\n" + "`If the agent didn't lead with the correct offer why?`,\n"
			+ "`If the agent didn't lead with the correct offer why? -Comment`,\n"
			+ "`Did the agent ask for the sale on product(s) that were offered?`,\n"
			+ "`Did agent ask for the sale on product(s) that were offer -c`,\n" + "`YES - Ask for Sale Tracking`,\n"
			+ "`YES - Ask for Sale Tracking -Comment`,\n"
			+ "`Did  agent attempt to overcome objections with regards to  sale`,\n"
			+ "`Did  agent attempt overcome objections with regards to sale -C`,\n"
			+ "`What was the reason the customer declined the sales offer?`,\n"
			+ "`What was reason customer declined  sales offer -C`,\n" + "`Did the agent close the sale?`,\n"
			+ "`Did the agent close the sale? -Comment`,\n" + "`YES - Products Sold`,\n"
			+ "`YES - Products Sold -Comment`,\n" + "`Retention Category Applicable`,\n"
			+ "`Retention Category Applicable -Comment`,\n" + "`Does this call require a save attempt/offer?`,\n"
			+ "`Does this call require a save attempt/offer? -Comment`,\n"
			+ "`Did the agent complete an account review for the customer?`,\n"
			+ "`Did  agent complete an account review for customer -C`,\n"
			+ "`What was the primary reason for the disconnect?`,\n"
			+ "`What was the primary reason for the disconnect? -Comment`,\n"
			+ "`Did agent ask discovery qus to determine appropriate save offer?`,\n" + "`not defined1`,\n"
			+ "`Did the agent make a save attempt?`,\n" + "`Did the agent make a save attempt? -Comment`,\n"
			+ "`YES - Save Attempt Product Tracking`,\n" + "`YES - Save Attempt Product Tracking -Comment`,\n"
			+ "`Did agent atmt to overcome objections with regard save attempt`,\n"
			+ "`overcome objections save attempt? -Comment`,\n"
			+ "`What save offers did the agent extend to the customer?`,\n"
			+ "`What save offers did the agent extend to the customer? -Comment`,\n"
			+ "`Did the agent save the customer?`,\n" + "`Did the agent save the customer? -Comment`,\n"
			+ "`Save Outcome Tracking - Offer Accepted`,\n" + "`Save Outcome Tracking - Offer Accepted -Comment`,\n"
			+ "`Did agent offer bill cycle end date as disconnect date`,\n"
			+ "`  bill cycle disconnect date? -Comment`,\n" + "`Which product(s) were saved?`,\n"
			+ "`Which product(s) were saved? -Comment`,\n" + "`not defined2`,\n" + "`not defined3`,\n"
			+ "`What products were added to the account?`,\n" + "`What products were added to the account? -Comment`,\n"
			+ "`Did the agent follow all applicable regulatory compliance?`,\n"
			+ "`Did agent follow all applicable regulatory compliance -c`,\n"
			+ "`NO - Applicable Compliance Tracking`,\n" + "`NO - Applicable Compliance Tracking -Comment`,\n"
			+ "`COMP: Did agent present disclosures and RCCs to the customer?`,\n"
			+ "`COMP: Did agent present disclosures and RCCs to the customer-c`,\n"
			+ "`NO - Applicable Disclosure Tracking`,\n" + "`NO - Applicable Disclosure Tracking -Comment`,\n"
			+ "`Did the agent read Disclosures/RCC's that were not applicable?`,\n"
			+ "`Did agent read Disclosures/RCC's that were not applicable -c`,\n"
			+ "`YES - Not Applicable Disclosure Tracking`,\n" + "`YES - Not Applicable Disclosure Tracking -Comment`,\n"
			+ "`information provided and/orders issued,  accurate and complete`,\n"
			+ "`information provided and/orders issued,accurate and complete -c`,\n" + "`NO - Entry Error Tracking`,\n"
			+ "`NO - Entry Error Tracking -Comment`,\n" + "`Did the agent meet recap expectations?`,\n"
			+ "`Did the agent meet recap expectations? -Comment`,\n" + "`NO - Recap Expectations Tracking`,\n"
			+ "`NO - Recap Expectations Tracking -Comment`,\n"
			+ "`Did the agent advise the customer of the NPS survey?`,\n"
			+ "`Did the agent advise the customer of the NPS survey? -Comment`,\n" + "`NO - NPS Survey Tracking`,\n"
			+ "`NO - NPS Survey Tracking -Comment`,\n"
			+ "`COMP: Based on call,account notations reflect what agent stated`,\n"
			+ "`COMP:Based on call,account notations reflect what agent stated-c`,\n"
			+ "`COMP Based call notations reflect what agent stated?Is Y,select`,\n"
			+ "`COMP Based call notation reflect what agent stated?Is Y,select-c`,\n"
			+ "`COMP: Did the agent follow the call handling process?`,\n"
			+ "`COMP: Did the agent follow the call handling process? -Comment`,\n"
			+ "`IF Did agent follow call handling process? Is  Y select`,\n"
			+ "`IF Did agent follow call handling process? Is  Y select-c`,\n"
			+ "`If the call was transferred where to?`,\n" + "`If the call was transferred where to? -Comment`,\n"
			+ "`Did the agent put the customer on hold?`,\n" + "`Did the agent put the customer on hold? -Comment`,\n"
			+ "`YES - Hold Process Tracking`,\n" + "`YES - Hold Process Tracking -Comment`,\n" + "`Hold Duration`,\n"
			+ "`Hold Duration -Comment`,\n" + "`COMP Did agent demonstrate integrity during customer contact?`,\n"
			+ "`COMP Did agent demonstrate integrity during customer contact?-c`,\n"
			+ "`NO - Integrity Demonstration Tracking`,\n" + "`NO - Integrity Demonstration Tracking -Comment`,\n"
			+ "`COMP: Did the agent mistreat the customer during the contact?`,\n"
			+ "`COMP Did agent mistreat customer during  contact? -c`,\n" + "`YES - Customer Mistreatment Tracking`,\n"
			+ "`YES - Customer Mistreatment Tracking -Comment`,\n" + "`Did the agent take ownership of the call?`,\n"
			+ "`Did the agent take ownership of the call? -Comment`,\n"
			+ "`No - Did the agent take ownership of the call?`,\n"
			+ "`No - Did the agent take ownership of the call? -Comment`,\n" + "`Was an Auto-Failure observed?`,\n"
			+ "`Was an Auto-Failure observed? -Comment`,\n"
			+ "`If Was an Auto-Failure observed? is Yes, please select`,\n"
			+ "`If Was an Auto-Failure observed? is Yes, please select -Comment`,\n"
			+ "`What was the overall rating of this observation?`,\n"
			+ "`What was the overall rating of this observation? -Comment`,\n"
			+ "`formname`) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
	
	public static String GET_QUERY = "Select * FROM `centurylinkdata` where STR_TO_DATE(`Call Date`,'%m/%d/%Y') >= ? \n" + 
			"and STR_TO_DATE(`Call Date`,'%m/%d/%Y') <= ?";
	
	
	public static String INSERT_QUERY_30_DAYS = "INSERT INTO `centurylinkdata_MTD_Autofail`\n" + "(\n"
			+ "`id`, `LobName1`,\n" + "`Campaign name`,\n" + "`Vendor Name`,\n" + "`Location Name`,\n" + "`Call Date`,\n"
			+ "`Duration`,\n" + "`ExternalID`,\n" + "`agent_external_id`,\n" + "`Call Type Name`,\n"
			+ "`CallDirectionName`,\n" + "`EvaluationId`,\n" + "`EvaluatorUserName`,\n" + "`EvaluatorFirstName`,\n"
			+ "`EvaluatorLastName`,\n" + "`Status Date`,\n" + "`EvaluationDuration`,\n" + "`RawPoints`,\n"
			+ "`NetScore`,\n" + "`Possible Points`,\n" + "`AutoFailed`,\n" + "`AuditorUserName`,\n"
			+ "`AuditorFirstName`,\n" + "`AuditorLastName`,\n" + "`Audit Status`,\n" + "`Audit Date`,\n"
			+ "`agent_first_name`,\n" + "`agent_last_name`,\n" + "`Supervisor`,\n" + "`Manager`,\n" + "`Manager2`,\n"
			+ "`MediaType1`,\n" + "`MediaCodecName1`,\n" + "`registered_affiliation`,\n" + "`Evaluator type`,\n"
			+ "`Type of Evaluation`,\n" + "`Customer State`,\n" + "`C.R.M.`,\n" + "`Language`,\n" + "`BTN/CBR`,\n"
			+ "`Auditor Comments`,\n" + "`Evaluator Comments`,\n" + "`Performance Area Notes`,\n"
			+ "`Invalidation Comments`,\n" + "`Form Change Comments`,\n" + "`Agent Comments`,\n"
			+ "`CTL QA Management Comments`,\n" + "`HQ Audit Feedback Loop`,\n" + "`Repeat Call/ Chat`,\n"
			+ "`Repeat Call/ Chat -Comment`,\n" + "`Product or Service Type (multi-select)`,\n"
			+ "`Product or Service Type (multi-select) -Comment`,\n" + "`Products on the CTL Account`,\n"
			+ "`Products on the CTL Account -Comment`,\n" + "`Products Available but not on CTL Account`,\n"
			+ "`Products Available but not on CTL Account -Comment`,\n" + "`Current HSI Speed`,\n"
			+ "`Current HSI Speed -Comment`,\n" + "`If HSI Upgrade Available - Highest Speed?`,\n"
			+ "`If HSI Upgrade Available - Highest Speed? -Comment`,\n" + "`Primary Reason for the Call`,\n"
			+ "`Primary Reason for the Call -Comment`,\n" + "`Billing Inquiry - Sub-reasons - PC`,\n"
			+ "`Billing Inquiry - Sub-reasons - PC -Comment`,\n" + "`BI - OTC Dispute - Sub-reasons - PC`,\n"
			+ "`BI - OTC Dispute - Sub-reasons - PC -Comment`,\n"
			+ "`COMP: Did the agent verify the caller thru authorized means?`,\n"
			+ "`COMP: Did the agent verify the caller -Comment`,\n" + "`NO - Verify caller`,\n"
			+ "`NO - Verify caller -Comment`,\n" + "`COMP: Did the agent verify and/or capture the email address?`,\n"
			+ "`COMP: Did the agent verify and/or capture the email -Comment`,\n" + "`NO - Email`,\n"
			+ "`NO - Email -Comment`,\n" + "`Did the agent utilize the SMS script?`,\n"
			+ "`Did the agent utilize the SMS script? -Comment`,\n"
			+ "`YES or NO - Did the agent utilize the SMS script?`,\n"
			+ "`YES or NO - Did the agent utilize the SMS script? -Comment`,\n" + "`Sales Category Applicable`,\n"
			+ "`Sales Category Applicable -Comment`,\n" + "`Did the agent ask discovery questions?`,\n"
			+ "`Did the agent ask discovery questions? -Comment`,\n" + "`YES - Discovery Questions`,\n"
			+ "`YES - Discovery Questions -Comment`,\n"
			+ "`Did the agent discuss a feature of the product or service?`,\n"
			+ "`Did the agent discuss a feature of the product -Comment`,\n" + "`YES - Feature Discussion`,\n"
			+ "`YES - Feature Discussion -Comment`,\n" + "`Did the agent offer product(s)?`,\n"
			+ "`Did the agent offer product(s)? -Comment`,\n" + "`Product Offer Tracking`,\n"
			+ "`Product Offer Tracking -Comment`,\n" + "`Did the agent lead with the correct offer?`,\n"
			+ "`Did the agent lead with the correct offer? -Comment`,\n" + "`Correct Offer Tracking`,\n"
			+ "`Correct Offer Tracking -Comment`,\n" + "`If the agent didn't lead with the correct offer why?`,\n"
			+ "`If the agent didn't lead with the correct offer why? -Comment`,\n"
			+ "`Did the agent ask for the sale on product(s) that were offered?`,\n"
			+ "`Did agent ask for the sale on product(s) that were offer -c`,\n" + "`YES - Ask for Sale Tracking`,\n"
			+ "`YES - Ask for Sale Tracking -Comment`,\n"
			+ "`Did  agent attempt to overcome objections with regards to  sale`,\n"
			+ "`Did  agent attempt overcome objections with regards to sale -C`,\n"
			+ "`What was the reason the customer declined the sales offer?`,\n"
			+ "`What was reason customer declined  sales offer -C`,\n" + "`Did the agent close the sale?`,\n"
			+ "`Did the agent close the sale? -Comment`,\n" + "`YES - Products Sold`,\n"
			+ "`YES - Products Sold -Comment`,\n" + "`Retention Category Applicable`,\n"
			+ "`Retention Category Applicable -Comment`,\n" + "`Does this call require a save attempt/offer?`,\n"
			+ "`Does this call require a save attempt/offer? -Comment`,\n"
			+ "`Did the agent complete an account review for the customer?`,\n"
			+ "`Did  agent complete an account review for customer -C`,\n"
			+ "`What was the primary reason for the disconnect?`,\n"
			+ "`What was the primary reason for the disconnect? -Comment`,\n"
			+ "`Did agent ask discovery qus to determine appropriate save offer?`,\n" + "`not defined1`,\n"
			+ "`Did the agent make a save attempt?`,\n" + "`Did the agent make a save attempt? -Comment`,\n"
			+ "`YES - Save Attempt Product Tracking`,\n" + "`YES - Save Attempt Product Tracking -Comment`,\n"
			+ "`Did agent atmt to overcome objections with regard save attempt`,\n"
			+ "`overcome objections save attempt? -Comment`,\n"
			+ "`What save offers did the agent extend to the customer?`,\n"
			+ "`What save offers did the agent extend to the customer? -Comment`,\n"
			+ "`Did the agent save the customer?`,\n" + "`Did the agent save the customer? -Comment`,\n"
			+ "`Save Outcome Tracking - Offer Accepted`,\n" + "`Save Outcome Tracking - Offer Accepted -Comment`,\n"
			+ "`Did agent offer bill cycle end date as disconnect date`,\n"
			+ "`  bill cycle disconnect date? -Comment`,\n" + "`Which product(s) were saved?`,\n"
			+ "`Which product(s) were saved? -Comment`,\n" + "`not defined2`,\n" + "`not defined3`,\n"
			+ "`What products were added to the account?`,\n" + "`What products were added to the account? -Comment`,\n"
			+ "`Did the agent follow all applicable regulatory compliance?`,\n"
			+ "`Did agent follow all applicable regulatory compliance -c`,\n"
			+ "`NO - Applicable Compliance Tracking`,\n" + "`NO - Applicable Compliance Tracking -Comment`,\n"
			+ "`COMP: Did agent present disclosures and RCCs to the customer?`,\n"
			+ "`COMP: Did agent present disclosures and RCCs to the customer-c`,\n"
			+ "`NO - Applicable Disclosure Tracking`,\n" + "`NO - Applicable Disclosure Tracking -Comment`,\n"
			+ "`Did the agent read Disclosures/RCC's that were not applicable?`,\n"
			+ "`Did agent read Disclosures/RCC's that were not applicable -c`,\n"
			+ "`YES - Not Applicable Disclosure Tracking`,\n" + "`YES - Not Applicable Disclosure Tracking -Comment`,\n"
			+ "`information provided and/orders issued,  accurate and complete`,\n"
			+ "`information provided and/orders issued,accurate and complete -c`,\n" + "`NO - Entry Error Tracking`,\n"
			+ "`NO - Entry Error Tracking -Comment`,\n" + "`Did the agent meet recap expectations?`,\n"
			+ "`Did the agent meet recap expectations? -Comment`,\n" + "`NO - Recap Expectations Tracking`,\n"
			+ "`NO - Recap Expectations Tracking -Comment`,\n"
			+ "`Did the agent advise the customer of the NPS survey?`,\n"
			+ "`Did the agent advise the customer of the NPS survey? -Comment`,\n" + "`NO - NPS Survey Tracking`,\n"
			+ "`NO - NPS Survey Tracking -Comment`,\n"
			+ "`COMP: Based on call,account notations reflect what agent stated`,\n"
			+ "`COMP:Based on call,account notations reflect what agent stated-c`,\n"
			+ "`COMP Based call notations reflect what agent stated?Is Y,select`,\n"
			+ "`COMP Based call notation reflect what agent stated?Is Y,select-c`,\n"
			+ "`COMP: Did the agent follow the call handling process?`,\n"
			+ "`COMP: Did the agent follow the call handling process? -Comment`,\n"
			+ "`IF Did agent follow call handling process? Is  Y select`,\n"
			+ "`IF Did agent follow call handling process? Is  Y select-c`,\n"
			+ "`If the call was transferred where to?`,\n" + "`If the call was transferred where to? -Comment`,\n"
			+ "`Did the agent put the customer on hold?`,\n" + "`Did the agent put the customer on hold? -Comment`,\n"
			+ "`YES - Hold Process Tracking`,\n" + "`YES - Hold Process Tracking -Comment`,\n" + "`Hold Duration`,\n"
			+ "`Hold Duration -Comment`,\n" + "`COMP Did agent demonstrate integrity during customer contact?`,\n"
			+ "`COMP Did agent demonstrate integrity during customer contact?-c`,\n"
			+ "`NO - Integrity Demonstration Tracking`,\n" + "`NO - Integrity Demonstration Tracking -Comment`,\n"
			+ "`COMP: Did the agent mistreat the customer during the contact?`,\n"
			+ "`COMP Did agent mistreat customer during  contact? -c`,\n" + "`YES - Customer Mistreatment Tracking`,\n"
			+ "`YES - Customer Mistreatment Tracking -Comment`,\n" + "`Did the agent take ownership of the call?`,\n"
			+ "`Did the agent take ownership of the call? -Comment`,\n"
			+ "`No - Did the agent take ownership of the call?`,\n"
			+ "`No - Did the agent take ownership of the call? -Comment`,\n" + "`Was an Auto-Failure observed?`,\n"
			+ "`Was an Auto-Failure observed? -Comment`,\n"
			+ "`If Was an Auto-Failure observed? is Yes, please select`,\n"
			+ "`If Was an Auto-Failure observed? is Yes, please select -Comment`,\n"
			+ "`What was the overall rating of this observation?`,\n"
			+ "`What was the overall rating of this observation? -Comment`,\n"
			+ "`formname`) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,"
			+ "?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";

}
